# Generated by Django 5.2.9 on 2026-01-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_total_price_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('poleras', 'Poleras'), ('polerones', 'Polerones'), ('pantalones', 'Pantalones'), ('accesorios', 'Accesorios')], default='poleras', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False, verbose_name='¿Es Nueva Colección?'),
        ),
    ]
