# Generated by Django 5.2.9 on 2026-01-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_category_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de Pago'), ('PAID', 'Pagado Exitosamente'), ('REJECTED', 'Rechazado/Anulado')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='webpay_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
